[service]
host = "localhost"
port = 10132
event_limit = 100000
listener_limit = 10000

[tls]
cert_path = "../../dev/certs/event-service.crt"
key_path = "../../dev/certs/event-service.key"
root_ca_path = "../../dev/certs/Chef_Automate_FAKE_Dev.crt"

[log]
format = "text"
level = "debug"

[handlers]
feed = "0.0.0.0:10121"
cfgingest = "0.0.0.0:10122"
authz = "0.0.0.0:10130"
