[service]
host = "localhost"
port = 14001
feed_interval = "30m"
asset_page_size = 100
reports_page_size = 1000
node_batch_size = 100

[tls]
key_contents =""
cert_contents = ""
root_cert_contents = ""

[mlsa]
accept = false

[log]
format = "text"
level = "info"

[storage]
database = "data_feed_service"
