backtrace       = 0
sentry_url      = ""
statsd_port     = -1
rails_env       = "production"
robots_disallow = ""
robots_allow    = "/"
secret_key_base = "9ee6f4446cc66e1398d4fe265f8714fcc46f7516aec5684fa2c3940e62c0329b597680e19a466ca5820eca9f0df99190331a"
rack_env        = "production"
lang            = "en_US.UTF-8"
ip_mode = "ipv4"

[app]
chef_server_url             = "https://api.chef.io"
rpm_signing_passphrase      = ''
owners_can_remove_artifacts = true
enforce_privacy             = false
api_item_limit              = 100
fqdn                        = 'localhost'
fqdn_sanitized              = ''
from_email                  = ''
google_analytics_id         = ''
segment_write_key           = ''
log_level                   = 'info'
serve_static_files          = true
cookbook                    = '' # ????
port                        = 10201
rails_log_to_stdout         = true
preload_app                 = true
worker_timeout              = 15
worker_processes            = 2
air_gapped_flag             = "false"
features                    = ["tools", "gravatar"]
user                        = "root"
group                       = "root"
log_directory               = ""
var_directory               = ""
protocol                    = "https"
allowed_host                = "localhost"


[nginx]
force_ssl = true
port      = 4000
ssl_port  = 4000

[app.announcement]
banner_enabled = false
text           = ""

[new_relic]
enabled     = false
license_key = ''
app_name    = 'Supermarket'

[urls]
#chef_domain        = "chef.io"
#progress_domain    = "progress.com"
#chef_www_url       = "https://www.chef.io"
#progress_www_url   = "https://www.progress.com"
#chef_status_url    = "https://status.chef.io"
#chef_blog_url      = "https://blog.chef.io/"
#chef_docs_url      = "https://docs.chef.io"
#chef_downloads_url = "https://downloads.chef.io"
#learn_chef_url     = "https://learn.chef.io"
#chef_training_url  = "https://www.chef.io/training"

[fips]
enabled      = false
openssl      = 0
omnibus_mode = ''

[fieri]
url                  = 'http://localhost:3000/fieri/jobs'
supermarket_endpoint =  'http://localhost:3000'
key                  = ''
foodcritic_tags      = ''
foodcritic_fail_tags = ''

[db]
host       = "localhost"
name       = "automate-supermarket"
user       = "automate-supermarket"
password   = "supermarket"
port = 10201
extensions = ['plpgsql', 'pg_trgm']
timeout=5000
pool_queue_timeout=2000
pool_max_size=20
pool_init_size=20
pool_queue_max=50

[log]
level="info"
rotation_max_bytes = 104857600
rotation_max_files = 10
max_error_logs_per_second = 1000

[datadog]
tracer_enabled = false
app_name       = "rails_app"

[github]
key                  = ""
secret               = ""
option_site          = ""
option_authorize_url = ""
access_token_url     = ""
enterprise_url       = ""
access_token         = ""
url                  = "https://github.com/"

[oauth2]
verify_ssl = false
url        = ""
app_id     = ""
secret     = ""

[redis]
host     = 'localhost'
port     = 16379
database = '0/supermarket'
jobq_url = ''

[s3]
access_key_id     = ""
secret_access_key = ""
region            = ""
bucket_name       = ""
cdn_url           = ""
private_objects   = true
path              = ""

[mlsa]
accept = true

[supermarket]
sql_retry_count=0
sql_retry_delay=10
abandoned_upload_cleanup_interval=1140000
deleted_data_cleanup_interval=420000
stream_download=true

[tls]
cert_contents = "-----BEGIN CERTIFICATE-----\nMIIEQTCCAimgAwIBAgIQMAAr9rPigovZluFWqiVn1TANBgkqhkiG9w0BAQsFADAp\nMScwJQYDVQQDEx5DaGVmIEF1dG9tYXRlIGE2ZWViYjk2OTEyOWIzNjMwHhcNMTgw\nMjE1MTU1MDU3WhcNMTkwODE1MTU1MDUzWjAdMRswGQYDVQQDExJsb2NhbC11c2Vy\nLXNlcnZpY2UwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDZFx+K2qZT\n0D+P7Ps1LIQFlb2vkUHX64gp0Gh/lquNOncQxWECkpznOrtZkH/4cq10WyC18gSM\nyWGhYoq8bjQbNJFC3luwX9Qy3Z9mguRjyV7Fk4oW80guVsDtFj6wtbpwKMt4WpTN\n4IqWNY/Ozc4VrcR6eRhqDUSYdYQ4jeD/m/4jfe3OJho2rVGfYmqIlHm+DKbnbpP/\nYYYsujIrfQaHf6YXrkG3kqAUGwSgLmu/9OEVecNFdNsN9AFAXdNvKNciyVrxp6iO\nmRCNhQCpX7XAjTKzZpX3YwlzKOp3jwcqftfhtbus9xh8BUVVrHNdamR5K/ZKW8qg\n7T0ys0fajEyVAgMBAAGjcTBvMA4GA1UdDwEB/wQEAwIDuDAdBgNVHSUEFjAUBggr\nBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYEFGxIbPEp28FNcXh1NBAAdGiCx1fC\nMB8GA1UdIwQYMBaAFI0V9OvZykKdSKFzVEYkAM2hVVwWMA0GCSqGSIb3DQEBCwUA\nA4ICAQA/oHZNDa9AEGKCDfRdhxUyka7rKsgRo9m/Tgkhr7khmszH5/f36h+VoslT\nkPpKiSzCug1QR2ZyDsSi+rRF43bQARr7ykzVv14Qxjgpu1FFEswynHwhrSxkacbZ\nGGd7E+oyClE2D6NLa1SxcxsZ46ejOuufnC9H7noF936tJBvMCcJ4OLMzTbJBQhLT\nM7UcjJLQV2Fjm7i9EPnBALZCqECh3W712bpDBI9Peh+lcQ/EpNMHL07xn+yOHfdW\nwYyOCrNSyq5a6C7tFjy/Y1XeCJc3zBxO3bu1zG3Rr9KR/gboyj7S7Y8l68RL0rdn\noQixeoeIRDR2kT+i0e1h6KcmHDSezf44DvSzs/BGtOCg/qnCFxkg2WtAiWNqXURB\nnQMmkGVIxYFVz7GV9Op5/PUy26J2HY0KxjRD1YzLdlQAoMkjGsUtxLd4flx47NV5\nZAQeUUpo+PCXLao9NTqvh/kGGMwkQfQrdJGt6M9j8dVaevcJrRsFTnOgHlim1IF7\naoIPYg1/3cYTgEiTwPiuDQEoN8FR0+MFs83nyKOpNzLYkloZIPVGOSs6QPpZvfkP\nwPXzeY3F+ODWzYLaNmms9BmZWwYY8abyPzzL1bsnuCzsO7fJX6dYSSlRk09EM2Uj\nRgcnofQymOTxmsxCASIbGrgQdYnOqpWC17qkoKa5XfbqH3M4XQ==\n-----END CERTIFICATE-----\n"
key_contents = "-----BEGIN RSA PRIVATE KEY-----\nMIIEpgIBAAKCAQEA2RcfitqmU9A/j+z7NSyEBZW9r5FB1+uIKdBof5arjTp3EMVh\nApKc5zq7WZB/+HKtdFsgtfIEjMlhoWKKvG40GzSRQt5bsF/UMt2fZoLkY8lexZOK\nFvNILlbA7RY+sLW6cCjLeFqUzeCKljWPzs3OFa3EenkYag1EmHWEOI3g/5v+I33t\nziYaNq1Rn2JqiJR5vgym526T/2GGLLoyK30Gh3+mF65Bt5KgFBsEoC5rv/ThFXnD\nRXTbDfQBQF3TbyjXIsla8aeojpkQjYUAqV+1wI0ys2aV92MJcyjqd48HKn7X4bW7\nrPcYfAVFVaxzXWpkeSv2SlvKoO09MrNH2oxMlQIDAQABAoIBAQDMsevw/pgkoVC9\nwgNgMRhPN9FC0WFXWePrIXLXE1ew8/a+3o3JYjsGIK/1FLZFqsP42dAvHwPBSEWB\naaxNXlBNcrSha47i8IjiaWxauYLmwEJXY/WqDDz8TJrfMsFr1/7ysNSiKC71LQsf\n9WMi6ZWvhUik/rfRj68lXnGM7eLAwDWnF6HMDypa+wb9li6SzIko+S1/d/Pa4SSz\nuCGprALzHsjV4owK8C3ZoUZWOij9xz0+z7zv3W7pOaFC6UNpBcdDAARm0x7oJeX/\nyEePQqcz2xBOv6km7APZJoVZOA0TBhaHGDMReMCLsDqfyH1MPiNsCd6JjWWe8Vmv\n9k3ZT4gFAoGBAN/Za/rEHER+FXvEJU7rFmImmEPjpdJlIRTQS4tOXlza8y/4NnPa\nuXvvGVZJKLqY92jsBSajxTjqpBAGC34gqu2al4q5xlcCnUPAAMzb3Xb70BpxO+cV\nJwt08p0/dQ66dfDXpHxo5BdpjgF5hIyV/ooqlbCHAQRyH9NDgIUOIUtrAoGBAPhF\nL0WmklYJkchwkAx+i8A7VNNUbcnyWuzE+Hdny3yTYfg4+0HmBw9hycZnKQZBtKPd\nBr9oRTt+s+qyVqYMF2UiquQpe2RVPgu5UcefFZ7yuuo95lyU83ZScuhfre9kzIyG\nKOsDLunndxxJ4Cc4YzmPXquo+3QPYUHHEETzxsf/AoGBAINWWhiDv+If6BL5/rnT\nDQsBgg0zIDPVyhcgL3LIxGzOuijHBYvsJTAmFUOfIRp6bY9OC6ekJy9B3IjaQxv5\nptBKB+gJH+olSohZux53UfVhwbQCBBeNPZ9nOoIwnUnK9TAeFhA4qrth30PWPIMP\n7oy6d6FfVKV7IFkgHePzam2JAoGBAMc9Lmyk+rcVQusqek+slpaUhsR58wmn9xQg\nFo4su/6jgHHluK3v3iaYAYe5bhDZVhBS5oFhOn4+dkCZEjR7a6L8KUylhaLFTd+2\nv0yF/KHshdhKCL6vwppoHFMjxcBikk0LtXa0vUd1O/91we93rxmYVw9Hs1Q2q4RQ\nLlxHjnUdAoGBALdWRuXVL/X3XcIV3dY8HymnDiZWxIPGqBclyjEmrJ3uosibB7mq\nhT8fK/YOuU7p95a3qu8+D412/NQl93ozUAtaR31OvobIxMPD8mH/d9VbyQkZYFmm\niEE3U10s9cumR65g9a/gLTQjVnjx7KnaSmapeV21G6zf7suGcoiLpY/w\n-----END RSA PRIVATE KEY-----\n"
root_cert_contents = "-----BEGIN CERTIFICATE-----\nMIIFEjCCAvqgAwIBAgIBATANBgkqhkiG9w0BAQsFADApMScwJQYDVQQDEx5DaGVm\nIEF1dG9tYXRlIGE2ZWViYjk2OTEyOWIzNjMwHhcNMTgwMjE1MTU1MDU0WhcNMTkw\nODE1MTU1MDU0WjApMScwJQYDVQQDEx5DaGVmIEF1dG9tYXRlIGE2ZWViYjk2OTEy\nOWIzNjMwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC7jAsj9NY/49ey\nSfpXq2hRMSwR9yA+5hb/ynq30N+Pdp9hkcDwlt/qm2ZA6VlW0adsS63/gEWO+zqY\n+auUGt5Nv3DOVz/Vn9yW6vZfU4XaILRtQsFat2ACxWtPcaHpHpTUIf3VJRQHB48m\nNrWL0DqEbKGXoADmVYs8kM5pRK2FsXuJKOKeY1QoUxh0m1tfw8OHwhyeYK0Y7q23\ncpLotWGw+N5Qq3PKhBP5MUVsdcn8ZblYGgSqpDTZbTOdxBgZa63CD0xUmt5ReDvh\nPVIalAjf22ZL9WlRrt1y+sxeu2cGlauPrvXlrZgkz2v1j7tEOjVSV9nZSBaG+fnB\nL2BUewJrBVwZuTonY4nKWuG6yJjbZ5JhUBhbb2kpGjFBaGTUr/LERP73FIAkVai7\nX0CZ3cu4Ggi/IfNxTGN/KX2z836ktVYBi9I6Jk5S4rB+XY0/XuU/v8PxK127asvc\nu2gbDjA2soYO7eO1cxiZWYtYJVkVhkAcTGyu6BTuNwlV+wLvzocX+p5j+IfDUdc5\nbVvO9wnBXAmeJQyaC6dL48wUNtUjG7e2oagT+LQ+45wkOSue4P2bM9spPwPnqBYR\nzJwIdIG5kG9uVo0n6tKz9H24KEYVd/zJDK/NArb8maJD7fc84yTr/+Ihrl7Du1FB\nXpG5cGWjAuG8VMcefer3Mo1FLzlcYQIDAQABo0UwQzAOBgNVHQ8BAf8EBAMCAQYw\nEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUjRX069nKQp1IoXNURiQAzaFV\nXBYwDQYJKoZIhvcNAQELBQADggIBAI77eRk9uhz8vsaM5lWFv9PvenZOibAJuKQd\ncivyI4Q6wmSZJsjzc8pf5ndwLyv1JdNENUSDoax+0Yem/dSUHy4ejuqG7IA8m4r9\nB0QNpvWN3W1SA97y7F4Cr0Al+PetskZVwxKR0jVthlf0VxAfe7KH06hWivVUelqP\nZIsipFxAfSAgIooW5yQli9Z5KuITYtFnvJs7Z6/qBbfZkdr7PCgi2zwSUAUBZduc\nRUdJlnlSg2zxmPxn7JVBXaO9MCTZdrv86sh2gM69mwlWOAtYPbBpETKOOLqQXVwH\nfUalbGSlLwuR4iZ76uTGSUt4861iGEBgecqg9fuU6ZnPD+M/Vwr1zFd6pheAMcDf\nWRKaUWYAnamqC17fz7PzeiAi6M71fbGrucYf78ErVThRbkOdw1C9ZesHbZNaV048\nwbmJr1oAtDSmWiUQGl2pwch5t/EwGgWhxXT/t8/52+P032QGkBhqQkxeWDHtMX3p\nhQHjkNvN5UtFcwm+FAQcaKWkDsX9kAzKwGAkaGWMeX2LjuIwgkqTRqSsHlRHPvnn\nFlGo19im6roN3BrjwDvCt7OuNnMYbGngfEuyFWtoo+HXQXotQ0Jz6/lRww31czis\nMvDvCKfo3LeaO8M2536Hc6bl9qORfUVCJqQwRQaLKwhua81WmjrYXtNkrz/BuWCS\nPTR05ZYW\n-----END CERTIFICATE-----\n"