# ======================== OpenSearch Configuration =========================
#
# NOTE: OpenSearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.opensearch.org
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: {{cfg.cluster.name}}
cluster.max_shards_per_node: {{cfg.cluster.max_shards_per_node}}
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
{{#if cfg.node.name ~}}
node.name: {{cfg.node.name}}
{{/if ~}}
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
# node.roles: [master-eligible, data, ingest]
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: 
  - {{pkg.svc_data_path}}/{{cfg.path.data}}
  - {{pkg.svc_var_path}}
#
# Path to log files:
#
path.logs: {{pkg.svc_var_path}}/{{cfg.path.logs}}
#
{{#if cfg.path.repo ~}}
path.repo: {{cfg.path.repo}}
{{/if ~}}
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
bootstrap.memory_lock: {{cfg.bootstrap.memory_lock}}
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# OpenSearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 192.168.0.1
{{#if cfg.network.host ~}}
network.bind_host: 0.0.0.0
network.publish_host: {{cfg.network.host}}
{{/if ~}}
#
# Set a custom port for HTTP:
#
http.port: {{cfg.network.port}}

transport.port: {{cfg.transport.port}}

# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when this node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discovery.seed_hosts: {{cfg.discovery.ping_unicast_hosts}}

discovery.zen.minimum_master_nodes: {{cfg.discovery.minimum_master_nodes}}

#
# Bootstrap the cluster using an initial set of master-eligible nodes:
#
cluster.initial_master_nodes: {{cfg.discovery.ping_unicast_hosts}}
#
# For more information, consult the discovery and cluster formation module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
{{#if cfg.gateway.recover_after_nodes ~}}
gateway.recover_after_nodes: {{cfg.gateway.recover_after_nodes}}
{{/if ~}}
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
action.destructive_requires_name: {{cfg.action.destructive_requires_name}}

######## Start OpenSearch Security  Configuration ########
#plugins.security.disabled: true
plugins.security.ssl.transport.pemcert_filepath: {{cfg.plugins.security.ssl.transport.pemcert_filepath}}
plugins.security.ssl.transport.pemkey_filepath: {{cfg.plugins.security.ssl.transport.pemkey_filepath}}
plugins.security.ssl.transport.pemtrustedcas_filepath: {{cfg.plugins.security.ssl.transport.pemtrustedcas_filepath}}
plugins.security.ssl.transport.enforce_hostname_verification: {{cfg.plugins.security.ssl.transport.enforce_hostname_verification}}
plugins.security.ssl.transport.resolve_hostname: {{cfg.plugins.security.ssl.transport.resolve_hostname}}
plugins.security.ssl.http.enabled: {{cfg.plugins.security.ssl.http.enabled}}
plugins.security.ssl.http.pemcert_filepath: {{cfg.plugins.security.ssl.http.pemcert_filepath}}
plugins.security.ssl.http.pemkey_filepath: {{cfg.plugins.security.ssl.http.pemkey_filepath}}
plugins.security.ssl.http.pemtrustedcas_filepath: {{cfg.plugins.security.ssl.http.pemtrustedcas_filepath}}
plugins.security.allow_unsafe_democertificates: {{cfg.plugins.security.allow_unsafe_democertificates}}
plugins.security.allow_default_init_securityindex: {{ cfg.plugins.security.allow_default_init_securityindex }}
plugins.security.authcz.admin_dn:
  {{ cfg.plugins.security.authcz.admin_dn }}
plugins.security.nodes_dn:
  {{ cfg.plugins.security.nodes_dn }}
plugins.security.audit.type: {{ cfg.plugins.security.audit.type }}
plugins.security.enable_snapshot_restore_privilege: {{ cfg.plugins.security.enable_snapshot_restore_privilege }}
plugins.security.check_snapshot_restore_write_privileges: {{ cfg.plugins.security.check_snapshot_restore_write_privileges }}
plugins.security.restapi.roles_enabled: {{  cfg.plugins.security.restapi.roles_enabled }}
plugins.security.system_indices.enabled: {{ cfg.plugins.security.system_indices.enabled }}
plugins.security.system_indices.indices: {{ cfg.plugins.security.system_indices.indices }}
node.max_local_storage_nodes: {{cfg.node.max_local_storage_nodes}}

######## End OpenSearch Security Configuration ########

{{#if cfg.plugins.cloud_aws_signer ~}}
cloud.aws.signer: {{cfg.plugins.cloud_aws_signer}}
{{/if ~}}

s3.client.default.protocol: {{ cfg.s3.client.default.protocol }}
s3.client.default.read_timeout: {{ cfg.s3.client.default.read_timeout }}
s3.client.default.max_retries: {{ cfg.s3.client.default.max_retries }}
s3.client.default.use_throttle_retries: {{ cfg.s3.client.default.use_throttle_retries }}
s3.client.default.endpoint: {{ cfg.s3.client.default.endpoint }}
