---
grpc: {{ cfg.service.host }}:{{ cfg.service.port }}
log-level: {{ cfg.logger.level }}
log-format: {{ cfg.logger.format }}

tls:
  cert_path: {{pkg.svc_config_path}}/service.crt
  key_path: {{pkg.svc_config_path}}/service.key
  root_ca_path: {{pkg.svc_config_path}}/root_ca.crt

database: {{cfg.storage.database}}
migrations-path: {{pkg.path}}/migrations
data-migrations-path: {{pkg.path}}/data-migrations
